---
identifier: "rdsdatabasebr"
allocated_storage: 10
engine: "postgres"
engine_version: "14"
instance_class: "db.t3.micro"
instance_name: "rdsinstancebr"
username: "bruno"
password: "teste1234"
skip_final_snapshot: false
